# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\usuario\OneDrive\Documentos\Semestre 2022-3\ciber 3\RedNeuronal\guiciber.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IA(object):
    def setupUi(self, IA):
        IA.setObjectName("IA")
        IA.resize(849, 600)
        IA.setStyleSheet("*{\n"
"    background-color: rgb(40, 100, 190);\n"
" font-family:     Comic Sans MS;\n"
"}\n"
"\n"
"QPushButton{\n"
"   background:#2d89ef;\n"
"   color: white;\n"
"   border: 2px solid;\n"
"   border-radius:15px;\n"
"   font-size:15px;        \n"
"}\n"
"QWidget #contenedorlienzo{\n"
"border: 2px solid;\n"
"}\n"
"\n"
"QLabel{\n"
"   font-size:20px;        \n"
"    color: white;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(IA)
        self.centralwidget.setObjectName("centralwidget")
        self.botonCargar = QtWidgets.QPushButton(self.centralwidget)
        self.botonCargar.setGeometry(QtCore.QRect(610, 180, 151, 41))
        self.botonCargar.setObjectName("botonCargar")
        self.botonEvaluar = QtWidgets.QPushButton(self.centralwidget)
        self.botonEvaluar.setGeometry(QtCore.QRect(630, 280, 101, 41))
        self.botonEvaluar.setObjectName("botonEvaluar")
        self.label_resultado = QtWidgets.QLabel(self.centralwidget)
        self.label_resultado.setGeometry(QtCore.QRect(556, 362, 261, 161))
        self.label_resultado.setText("")
        self.label_resultado.setObjectName("label_resultado")
        self.contenedorlienzo = QtWidgets.QWidget(self.centralwidget)
        self.contenedorlienzo.setGeometry(QtCore.QRect(30, 30, 511, 531))
        self.contenedorlienzo.setObjectName("contenedorlienzo")
        IA.setCentralWidget(self.centralwidget)

        self.retranslateUi(IA)
        QtCore.QMetaObject.connectSlotsByName(IA)

    def retranslateUi(self, IA):
        _translate = QtCore.QCoreApplication.translate
        IA.setWindowTitle(_translate("IA", "MainWindow"))
        self.botonCargar.setText(_translate("IA", "Cargar Imagen"))
        self.botonEvaluar.setText(_translate("IA", "Evaluar"))
